### ISSUE TITLE
finish zos_client

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#136]
https://github.com/Jumpscale/lib9/tree/master/JumpScale9Lib/clients/zero_os

**Comment by zaibon** [comment]
I have questions about this.

1. Since everything has been copied into Jumpscale, what are we going to do with https://github.com/zero-os/0-core/tree/master/client/py-client ?
Cause now we have 2 version of the same client. 
Also with each release of 0-core. We use to release the corresponding python client. Now that is part of Jumpscale we can't do this anymore, I can see how this will create trouble if we don't have a release of Jumpscale for each release of 0-core.

2. We need to integrate https://github.com/zero-os/0-orchestrator/tree/master/pyclient/zeroos/orchestrator/sal into Jumpscale as well. I'll need these SAL/libs to work on 0-robot. This will probably required some refactor of the SAL from orchestrator.
How do we proceed for that ?

**Comment by despiegk** [comment]
1: we already discussed this, this is ok, we have this same issue for any client, we need to be backwards compatible at some point in time and be able to ask server version it has
2: no-idea
