### ISSUE TITLE
gitea client broken?

### ISSUE THREAD

**Issue by despiegk** [Jumpscale/lib9#172]
![image](https://user-images.githubusercontent.com/6021844/36072638-90764d28-0f2b-11e8-9e41-da4f4b607f95.png)

**Comment by despiegk** [comment]
same issue for IYO client, maybe goraml re-generation?

**Comment by despiegk** [comment]
the problem is with:
`class DatetimeHandler(object, JSBASE)`
cannot have both in same method

**Comment by serboctor** [comment]
The generated code from go-raml does NOT inherit from JSBASE. This was manually added in this commit https://github.com/Jumpscale/lib9/commit/fd5cc5d82560fb689c364e0bda85ee7985ae2795#diff-90b1efe0392a9159143b6592d8ee029f and this is a python error because a class can't inherit from both object and JSBASE.

**Comment by rkhamis** [comment]
I removed it. Works now
