### ISSUE TITLE
Grid capacity: track used capacity 

### ISSUE THREAD

**Issue by zaibon** [Jumpscale/lib9#310]
Currently the capacity tracked is only the raw capacity of the node. We also need to track the different deployed capacity to have a better view on the usage of the grid.

The node robot needs to track
- reserved capacity units
- actual capacity used units
and publish these along with the raw capacity to the central repository.

Besides publishing this every two hours, intermediate updates should also be done when workloads are deployed or removed.

**Comment by FastGeert** [comment]
Currently the capacity tracked is only the raw capacity of the node. 
To be able to use the central registration for capacity planning we also need to be able to
- Track used public ips
- Track used private networks (vxlan ids)
on a per farm basis.

Besides that we also need to track physical reserved capacity such as
- Memory in MRU
- Disk space per ZDB in SRU & HRU

Based on these reservations the central registration should offer the following rest api's to be used by digital me robot:
- List nodes
  - Parameters
    - Farm Id: Id of farm
  - Result: List of nodes with the following properties
    - Free MRU
    - List of ZDB with their free number of SRU & HRU
- Make a reservation
  - Parameters
    - List of Reservation objects with the following properties
      - Reservation Id: Unique id for the reservation (uuid.uuid4())
      - Node Id: Id of node on which a reservation should be created. Ignored in case of PIRU or PNRU reservation.
      - ZDB Id: Ignored unless in case of HRU or SRU reservation
      - Capacity unit type: [MRU/SRU/HRU/PIRU/]
      - Amount: Number of units to reserve
  - Result: 
    - Success: All reservations could be atomically made.
      - List of PIRU & PNRU reservations and their resulting pub ip or vxlan id
    - Failure: Was not possible to achieve success. The client might need to requery the free capacity and recalculate the reservations, and try again.

To be able to monitor if reserved capacity is actually used, the node robots should also receive the reservation ids when they deploy something, so that they can also report the reservation usage back to the central registration. If the node robot does not report the actual usage of a reservation when doing its reporting cycle, any reservation that is older than 1 hour and not reported back is considered not used and will be wiped.

**Comment by FastGeert** [comment]
Currently the capacity tracked is only the raw capacity of the node. We also need to track the different deployed capacity to have a better view on the usage of the grid.

The node robot needs to track
- reserved capacity units
- actual capacity used units
and publish these along with the raw capacity to the central repository.

Besides publishing this every two hours, intermediate updates should also be done when workloads are deployed or removed.

**Comment by zaibon** [comment]
Server side have been updated to support tracking of the new metrics. 
Still to do:
- update [capacity SAL](https://github.com/Jumpscale/lib9/blob/development/JumpScale9Lib/clients/zero_os/sal/Capacity.py) to allow to pass these metrics in the registration
- update the template to use the new methos of the sal to register the new metrics

**Comment by zaibon** [comment]
@arahmanhamdy make sure to base your work on : https://github.com/Jumpscale/lib9/pull/323
